apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{values.name}}-on-pull-request
  namespace: {{values.namespace}}
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/pipelines/nodejs-build.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/show-sbom.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/summary.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/init.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/prefetch-dependencies.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/buildah.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/source-build.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/deprecated-image-check.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/clair-scan.yaml"
    pipelinesascode.tekton.dev/task: "https://github.com/jduimovich/dance-standard-pipelines/blob/main/pac/tasks/sast-snyk-check.yaml"    
spec: 
  params:
  - name: dockerfile
    value: {{values.dockerfileLocation}}
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: {{values.image}}:on-pr-{{revision}}
  - name: path-context
    value: {{values.buildContext}}
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: nodejs-build
 